site_name: Mkdocs Versioning Example
site_url: https://egrosdou01.github.io/mkdocs-versioning-example/

repo_name: egrosdou01/mkdocs-versioning-example
repo_url: https://github.com/egrosdou01/mkdocs-versioning-example
edit_uri: ""

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ""
- attr_list
- md_in_html
- footnotes
- pymdownx.critic
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:zensical.extensions.emoji.twemoji ""
    emoji_generator: !!python/name:zensical.extensions.emoji.to_svg ""
theme:
  custom_dir: overrides
  features:
  - content.code.copy
  - search.share
  - navigation.footer
  - navigation.instant.progress
  - content.code.annotate
  palette:
  - scheme: default
    toggle:
      icon: lucide/sun
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: lucide/moon
      name: Switch to light mode
extra_javascript:
- javascript/extra.js
extra:
  version:
    provider: mike
    alias: true
    default:
    - dev
plugins:
- search
